version: "3"
services:
  mysql-standalone:
    image: mysql:5.6
    ports:
      - 3305:3306
    environment:
      - MYSQL_DATABASE=swaproj
      - MYSQL_ROOT_PASSWORD=1986
  app:
    build: .
    ports:
      - 8086:8086
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/swaproj?autoReconnect=true&useSSL=false
    depends_on:
      - mysql-standalone